// BAKR-22: the agents.json v1 -> v2 migration, run entirely inside
// `parseAgentStoreState` (agent-model.ts) — pure, in-memory, no I/O. See
// that function's own doc, and `migrateV1AgentRecord`/`migrateV1LaunchRecord`,
// for the exact rule this test locks in. Two cases the epic asked for by
// name: a store written by `a88bbee1` (main before this ticket), and a
// record whose `liveSessionId` is a pre-BAKR-22 FORK of its
// `durableSessionId` — the subtle case, because the migration must choose
// which of the two becomes the new `restoreTarget`.

import { describe, expect, test } from "bun:test";
import { parseAgentStoreState, serializeAgentStoreState, type AgentStoreState } from "../../src/agent-model";
import type { ClaimKey } from "../../src/claim-key-resolve";

const KEY = "/tmp/some-dir" as ClaimKey;

/** Builds a v1-shaped `agents.json` payload exactly as `a88bbee1` would have written it — the pre-BAKR-22 wire format, never generated by current code, so this is spelled out by hand rather than reused from any live serializer. */
function v1Payload(opts: {
  agentId?: string;
  durableSessionId?: string | null;
  liveSessionId?: string | null;
  launchPriorSessionId?: string | null;
  launchError?: string | null;
}): string {
  const agentId = opts.agentId ?? "@v1agent000000000000";
  return JSON.stringify({
    version: 1,
    agents: {
      [agentId]: {
        id: agentId,
        name: null,
        directory: KEY,
        state: "on",
        createdAt: 1000,
        durableSessionId: opts.durableSessionId ?? null,
        liveSessionId: opts.liveSessionId ?? null,
      },
    },
    retiredIds: [],
    launches:
      opts.launchPriorSessionId !== undefined
        ? [
            {
              attemptId: "attempt-1",
              agentId,
              key: KEY,
              priorSessionId: opts.launchPriorSessionId,
              attemptedAt: 2000,
              launchShortId: null,
              error: opts.launchError ?? null,
            },
          ]
        : [],
    restoreAttemptCounts: {},
    pendingCreations: [],
  });
}

describe("agents.json v1 -> v2 migration (BAKR-22)", () => {
  test("ORDINARY case: durableSessionId === liveSessionId -> restoreTarget derived from it, birthSessionId carried unchanged", () => {
    const sessionId = "3049aceb-aa21-4b9d-9d81-b49fa4c0ab01";
    const source = v1Payload({ durableSessionId: sessionId, liveSessionId: sessionId });
    const result = parseAgentStoreState(source);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const agent = result.state.agents["@v1agent000000000000"];
    expect(agent).toBeDefined();
    expect(agent?.birthSessionId).toBe(sessionId);
    expect(agent?.restoreTarget).toEqual({ sessionId, shortId: sessionId.slice(0, 8) });
  });

  test("THE SUBTLE CASE — a v1 record whose liveSessionId is a pre-BAKR-22 FORK of its durableSessionId: restoreTarget prefers liveSessionId (the more recent), birthSessionId stays the ORIGINAL durable id", () => {
    const birthId = "3049aceb-aa21-4b9d-9d81-b49fa4c0ab01";
    const forkedLiveId = "57fff143-3aa7-421f-9b46-66c1036ca1f8"; // BAKR-18's own measured fork, reused verbatim as a realistic value
    const source = v1Payload({ durableSessionId: birthId, liveSessionId: forkedLiveId });
    const result = parseAgentStoreState(source);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const agent = result.state.agents["@v1agent000000000000"];
    // The falsifier this test is stated against: if migration instead
    // preferred `durableSessionId` here, `restoreTarget.sessionId` would
    // equal `birthId`, not `forkedLiveId` — and the next `respawn` would
    // target the ORIGINAL pre-fork short id, discarding whatever the fork
    // actually contains. That would be the exact rewind bug this ticket
    // exists to fix, reintroduced by the migration itself.
    expect(agent?.restoreTarget?.sessionId).toBe(forkedLiveId);
    expect(agent?.restoreTarget?.shortId).toBe(forkedLiveId.slice(0, 8));
    expect(agent?.birthSessionId).toBe(birthId);
    expect(agent?.birthSessionId).not.toBe(agent?.restoreTarget?.sessionId);
  });

  test("a v1 agent with NO session at all yet (fresh launch never resolved) migrates to restoreTarget: undefined, birthSessionId: undefined", () => {
    const source = v1Payload({ durableSessionId: null, liveSessionId: null });
    const result = parseAgentStoreState(source);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const agent = result.state.agents["@v1agent000000000000"];
    expect(agent?.birthSessionId).toBeUndefined();
    expect(agent?.restoreTarget).toBeUndefined();
  });

  test("a v1 RESTORE launch record (priorSessionId set) migrates to a respawn-kind attemptKey, short id derived the SAME way the agent's own restoreTarget would be — so a migrated give-up record and a future respawn attempt key against the same value (B13 survives the migration)", () => {
    const priorSessionId = "3049aceb-aa21-4b9d-9d81-b49fa4c0ab01";
    const source = v1Payload({ durableSessionId: priorSessionId, liveSessionId: priorSessionId, launchPriorSessionId: priorSessionId, launchError: "gave up" });
    const result = parseAgentStoreState(source);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.state.launches).toHaveLength(1);
    const launch = result.state.launches[0];
    expect(launch?.attemptKey).toEqual({ kind: "respawn", shortId: priorSessionId.slice(0, 8) });
    expect(launch?.error).toBe("gave up");
    // The B13 property this migration must preserve: the derived key here
    // is byte-identical to the agent's own migrated restoreTarget.shortId.
    const agent = result.state.agents["@v1agent000000000000"];
    expect(agent?.restoreTarget?.shortId).toBeDefined();
    expect((launch?.attemptKey as { shortId: string }).shortId).toBe(agent?.restoreTarget?.shortId as string);
  });

  test("a v1 FRESH launch record (priorSessionId absent) migrates to attemptKey: undefined", () => {
    const source = v1Payload({ durableSessionId: null, liveSessionId: null, launchPriorSessionId: null, launchError: "crashed" });
    const result = parseAgentStoreState(source);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.state.launches[0]?.attemptKey).toBeUndefined();
  });

  test("a genuine store written by a88bbee1 (main, pre-BAKR-22) — the literal shape, not reconstructed — stays loadable end to end", () => {
    // Spelled out as the actual JSON text a88bbee1's serializeAgentStoreState
    // would have produced, rather than built through any current helper —
    // this is what "a store written by a88bbee1 stays loadable" means as a
    // falsifiable claim: if agent-model.ts's CURRENT parser rejected this
    // exact byte shape, this test fails.
    const raw = JSON.stringify({
      version: 1,
      agents: {
        "@abc123def456ghi789": {
          id: "@abc123def456ghi789",
          name: "worker-one",
          directory: KEY,
          state: "on",
          createdAt: 1789120000000,
          durableSessionId: "aaaaaaaa-0000-1111-2222-333333333333",
          liveSessionId: "aaaaaaaa-0000-1111-2222-333333333333",
        },
      },
      retiredIds: ["@retired000000000000"],
      launches: [],
      restoreAttemptCounts: { "@abc123def456ghi789": 1 },
      pendingCreations: [],
    });
    const result = parseAgentStoreState(raw);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.state.retiredIds).toEqual(["@retired000000000000"]);
    expect(result.state.restoreAttemptCounts["@abc123def456ghi789"]).toBe(1);
    const agent = result.state.agents["@abc123def456ghi789"];
    expect(agent?.name).toBe("worker-one");
    expect(agent?.birthSessionId).toBe("aaaaaaaa-0000-1111-2222-333333333333");
    expect(agent?.restoreTarget).toEqual({ sessionId: "aaaaaaaa-0000-1111-2222-333333333333", shortId: "aaaaaaaa" });

    // And re-serializing writes it back out as v2, never v1 again — the
    // migration is a one-way, in-memory upgrade; the NEXT save is what
    // actually commits the new shape to disk (agent-store-io.ts's `save`
    // always serializes AGENT_STORE_VERSION, which is 2).
    const reserialized = serializeAgentStoreState(result.state);
    const reparsed = JSON.parse(reserialized) as { version: number };
    expect(reparsed.version).toBe(2);
  });

  test("a native v2 store round-trips through serialize/parse with no transformation", () => {
    const state: AgentStoreState = {
      agents: {
        "@nativev2000000000000": {
          id: "@nativev2000000000000",
          name: undefined,
          directory: KEY,
          state: "on",
          createdAt: 5000,
          birthSessionId: "birth-session-uuid",
          restoreTarget: { sessionId: "current-session-uuid", shortId: "current-" },
        },
      },
      retiredIds: [],
      launches: [
        {
          attemptId: "a1",
          agentId: "@nativev2000000000000",
          key: KEY,
          attemptKey: { kind: "forkFrom", sessionId: "pre-fork-session" },
          attemptedAt: 6000,
          launchShortId: "newshort",
          error: undefined,
        },
      ],
      restoreAttemptCounts: {},
      pendingCreations: [],
    };
    const roundTripped = parseAgentStoreState(serializeAgentStoreState(state));
    expect(roundTripped.ok).toBe(true);
    if (!roundTripped.ok) return;
    expect(roundTripped.state).toEqual(state);
  });

  test("an unrecognized version (neither 1 nor 2) is malformed, never silently coerced", () => {
    const result = parseAgentStoreState(JSON.stringify({ version: 3, agents: {}, retiredIds: [], launches: [], restoreAttemptCounts: {}, pendingCreations: [] }));
    expect(result.ok).toBe(false);
  });
});
